
//import javax.swing.JComboBox;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import java.io.File;
//import java.io.FileWriter;
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */

/**
 *
 * @author user2
 */
public class Ventana extends javax.swing.JFrame {

    File archivo = new File("Historial.txt");
    int cont = 0;
    private Metodos bolita = null;
    private Ticketeador ticketeador = null;
    String txthistorial = "";

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        bolita = new Metodos(cmbProducto, txtCantidad);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        tbpKiosco = new javax.swing.JTabbedPane();
        pnlCobranza = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblMetodopago = new javax.swing.JLabel();
        cmbMetodoPago = new javax.swing.JComboBox();
        lblDescuento = new javax.swing.JLabel();
        btnAceptarCobranza = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbMesCobranza = new javax.swing.JComboBox();
        btnTicket = new javax.swing.JButton();
        pnlVentaDia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        pnlHistorial = new javax.swing.JPanel();
        jspHistorial = new javax.swing.JScrollPane();
        txtHistorial = new javax.swing.JTextArea();
        btnDar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlGxM = new javax.swing.JPanel();
        lblMes = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaGanancia = new javax.swing.JTextArea();
        btnDameee = new javax.swing.JButton();
        mnubPrincipal = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuiNuevo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProducto.setText("Producto");

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Alfajor", "Sandwich", "Palito de la selva", "Gomita", "Turron", "Chupetin", "Criollo", "Factura", "Papas Fritas", "Toddy's", "Pepitos", "Oreos", "Gaseosa de 1l", "Gaseosa de 2l", "Gaseosa de 350ml" }));
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        lblMetodopago.setText("Método de pago?");

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Credito o Debito" }));
        cmbMetodoPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbMetodoPagoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbMetodoPagoMouseEntered(evt);
            }
        });
        cmbMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodoPagoActionPerformed(evt);
            }
        });

        btnAceptarCobranza.setText("Aceptar");
        btnAceptarCobranza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCobranzaActionPerformed(evt);
            }
        });

        jLabel3.setText("Mes");

        cmbMesCobranza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        btnTicket.setText("Ticket?");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCobranzaLayout = new javax.swing.GroupLayout(pnlCobranza);
        pnlCobranza.setLayout(pnlCobranzaLayout);
        pnlCobranzaLayout.setHorizontalGroup(
            pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDescuento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCobranzaLayout.createSequentialGroup()
                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCobranzaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnAceptarCobranza))
                    .addGroup(pnlCobranzaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCobranzaLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addGap(58, 58, 58))
                            .addComponent(lblMetodopago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCobranzaLayout.createSequentialGroup()
                                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2)))))
                .addGap(43, 43, 43)
                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCobranzaLayout.createSequentialGroup()
                        .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMetodoPago, 0, 1, Short.MAX_VALUE)
                            .addComponent(txtCantidad)
                            .addComponent(cmbProducto, 0, 1, Short.MAX_VALUE)
                            .addComponent(cmbMesCobranza, 0, 1, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(pnlCobranzaLayout.createSequentialGroup()
                        .addComponent(btnTicket)
                        .addContainerGap(82, Short.MAX_VALUE))))
        );
        pnlCobranzaLayout.setVerticalGroup(
            pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCobranzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMesCobranza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMetodopago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(pnlCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCobranza)
                    .addComponent(btnTicket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpKiosco.addTab("Cobranza", pnlCobranza);

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha y hora", "Artículo", "Medio de Pago", "Total en $"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablita);
        tablita.getColumnModel().getColumn(0).setResizable(false);

        javax.swing.GroupLayout pnlVentaDiaLayout = new javax.swing.GroupLayout(pnlVentaDia);
        pnlVentaDia.setLayout(pnlVentaDiaLayout);
        pnlVentaDiaLayout.setHorizontalGroup(
            pnlVentaDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        pnlVentaDiaLayout.setVerticalGroup(
            pnlVentaDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVentaDiaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
        );

        tbpKiosco.addTab("Ventas del Día", pnlVentaDia);

        txtHistorial.setColumns(20);
        txtHistorial.setRows(5);
        jspHistorial.setViewportView(txtHistorial);

        btnDar.setText("Dame Historial");
        btnDar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHistorialLayout = new javax.swing.GroupLayout(pnlHistorial);
        pnlHistorial.setLayout(pnlHistorialLayout);
        pnlHistorialLayout.setHorizontalGroup(
            pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHistorialLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlHistorialLayout.createSequentialGroup()
                        .addComponent(jspHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(pnlHistorialLayout.createSequentialGroup()
                        .addComponent(btnDar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(45, 45, 45))))
        );
        pnlHistorialLayout.setVerticalGroup(
            pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHistorialLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGap(35, 35, 35)
                .addComponent(jspHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpKiosco.addTab("Historial", pnlHistorial);

        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes.setText("Mes");

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        txtaGanancia.setColumns(20);
        txtaGanancia.setRows(5);
        jScrollPane2.setViewportView(txtaGanancia);

        btnDameee.setText("Dame la ganancia de ese mes");
        btnDameee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDameeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGxMLayout = new javax.swing.GroupLayout(pnlGxM);
        pnlGxM.setLayout(pnlGxMLayout);
        pnlGxMLayout.setHorizontalGroup(
            pnlGxMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGxMLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlGxMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGxMLayout.createSequentialGroup()
                        .addComponent(lblMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(cmbMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGxMLayout.createSequentialGroup()
                        .addGroup(pnlGxMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDameee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(55, 55, 55))))
        );
        pnlGxMLayout.setVerticalGroup(
            pnlGxMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGxMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGxMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDameee, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        tbpKiosco.addTab("Ganancia x Mes", pnlGxM);

        mnuArchivo.setText("Archivo");

        mnuiNuevo.setText("Nuevo");
        mnuiNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNuevoActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuiNuevo);

        jMenuItem1.setText("Exportar Historial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuArchivo.add(jMenuItem1);

        mnubPrincipal.add(mnuArchivo);

        jMenu4.setText("algo");
        mnubPrincipal.add(jMenu4);

        setJMenuBar(mnubPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpKiosco)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpKiosco)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNuevoActionPerformed
        txtCantidad.setText("");
        cmbProducto.setSelectedIndex(0);
    }//GEN-LAST:event_mnuiNuevoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            File archivo = new File("texto.txt");

            FileWriter escribir = new FileWriter(archivo, true);

            String dato = "cosa escrita";

            escribir.write(dato);

            escribir.close();
        } //Si existe un problema al escribir cae aqui
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Paso algo malo", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        ticketeador.setVisible(true);
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnAceptarCobranzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCobranzaActionPerformed

        // variables
        String pedido = bolita.getPedido();
        ticketeador = new Ticketeador(pedido);
        String[] precios = bolita.getPrecios();
        double precio = bolita.getPrecio();
        bolita.setCombo(cmbProducto);
        ticketeador.setBolita(bolita);
        boolean bandera = true;
        ObtenerFechaHora ofh = new ObtenerFechaHora();
        String tipoOper = "" + cmbMetodoPago.getSelectedItem();
        String fecha = ofh.dameFechaHora();

        int index = cmbProducto.getSelectedIndex();
        index--;
        int cantidad = 0;

        // proceso
        try {
            // entrada
            cantidad = Integer.parseInt(txtCantidad.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Porfavor ingrese algo en"
                    + " el sector cantidad", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if ("Efectivo".equals(tipoOper)) {
            precio = bolita.getPrecioEfectivo(Integer.parseInt(precios[index]), cantidad);
        } else {
            precio = bolita.getPrecioDebito(Integer.parseInt(precios[index]), cantidad);
        }

//
//        for (int i = 0; i < cmbMes.getItemCount(); i++) {
            try {

               
                File archivo = new File("Ganancias/"+cmbMesCobranza.getModel().getSelectedItem()+".txt");

                FileWriter escribir = new FileWriter(archivo, true);

                escribir.write(""+precio+"\n");

                escribir.close();

            } //Si existe un problema al escribir cae acá
            catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "No se creo el archivo del mes", "Error", JOptionPane.WARNING_MESSAGE);
            }
//        }
      

        try {
            File archivo = new File("Historial.txt");

            FileWriter escribir = new FileWriter(archivo, true);

            escribir.write("Se compro lo siguiente: "+pedido + " En una cantidad de " + cantidad+"El dia " + fecha +" Se pago en: "+ tipoOper+" Un total de:$ " + precio + "\n");

            escribir.close();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se creo el archivo del Historial", "Error", JOptionPane.WARNING_MESSAGE);
        }

        while (bandera) {
            try {
                for (int j = 0; j < 4; j++) {

                    if (j == 0) {
                        tablita.setValueAt(fecha, cont, j);

                    }
                    if (j == 1) {
                        tablita.setValueAt(pedido, cont, j);
                    }

                    if (j == 2) {
                        tablita.setValueAt(tipoOper, cont, j);
                    }
                    if (j == 3) {
                        tablita.setValueAt(precio, cont, j);

                    }

                }

                cont++;

            } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
                JOptionPane.showMessageDialog(rootPane, "ERROR, DEMASIADOS DATOS", "Error", JOptionPane.WARNING_MESSAGE);
            }
            bandera = false;

        }
    }//GEN-LAST:event_btnAceptarCobranzaActionPerformed

    private void cmbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoPagoActionPerformed

    private void cmbMetodoPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMetodoPagoMouseEntered
        lblDescuento.setText("pagos en efectivo tienen un %5 de descuento");
    }//GEN-LAST:event_cmbMetodoPagoMouseEntered

    private void cmbMetodoPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMetodoPagoMouseExited
        lblDescuento.setText("");
    }//GEN-LAST:event_cmbMetodoPagoMouseExited

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
        //entrada o salida
    }//GEN-LAST:event_cmbProductoActionPerformed

    private void btnDarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarActionPerformed
        FileReader leedor = null;
        try {
            String cH = "";
            leedor = new FileReader("Historial.txt");
            BufferedReader jajaja = new BufferedReader(leedor);


            try {
                String linea = jajaja.readLine();
                while ((txthistorial = linea) != null) {
                    cH += linea + "\n";
                    linea = jajaja.readLine();
                }
                if (!txtHistorial.getText().equals(txthistorial)) {
                    txtHistorial.setText("");
                    txtHistorial.setText(cH);
                }

            } catch (IOException ex) {
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                leedor.close();
            } catch (IOException ex) {

                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Historial Eliminado", "Error", JOptionPane.WARNING_MESSAGE);
        txtHistorial.setText("");
        archivo.delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDameeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDameeeActionPerformed
        try {
            // VARIABLES
            FileReader lector;
            BufferedReader archivo;
            String linea;
            float total = 0;
            lector = new FileReader("Ganancias/"+cmbMes.getSelectedItem() + ".txt");
            archivo = new BufferedReader(lector);

            linea = archivo.readLine();

            while (linea!=null) {
                total += Float.parseFloat(linea);
                linea = archivo.readLine();
            }
            
            
            txtaGanancia.setText("" + total);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDameeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());



        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCobranza;
    private javax.swing.JButton btnDameee;
    private javax.swing.JButton btnDar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTicket;
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JComboBox cmbMesCobranza;
    private javax.swing.JComboBox cmbMetodoPago;
    private javax.swing.JComboBox cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspHistorial;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMetodopago;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuBar mnubPrincipal;
    private javax.swing.JMenuItem mnuiNuevo;
    private javax.swing.JPanel pnlCobranza;
    private javax.swing.JPanel pnlGxM;
    private javax.swing.JPanel pnlHistorial;
    private javax.swing.JPanel pnlVentaDia;
    private javax.swing.JTable tablita;
    private javax.swing.JTabbedPane tbpKiosco;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtHistorial;
    private javax.swing.JTextArea txtaGanancia;
    // End of variables declaration//GEN-END:variables
}
